### PR TITLE
Only download binaries for the platform

### PR DESCRIPTION
**Pull request by rajendrant**
To keep the installed package size small, only needed binaries for the platform are downloaded and uncompressed. This CL also enables Travis CI builds for windows.

### CODE REVIEW

**Comment by rajendrant** [comment]
Fixes #20

**Comment by derhuerst** [comment]
The `build` script is being executed as *build time*, then all binaries are being published to npm. I assume you intend to install ffmpeg at install time?

**Comment by rajendrant** [comment]
Ah. Right. I wanted them to be downloaded at install time.
Is that a big deviation from the current mechanism ?
I did not think it was packaged and published to npm (since the travis CI builds were passing). 

I will explore more on making it as an install step ?

**Comment by derhuerst** [comment]
> I will explore more on making it as an install step ?

I can see why this is the obvious way to got, but I'd like to avoid creating another npm package with install hooks. The npm reliability & security of the npm ecosystem is already in a sad state, so I like to avoid contributing to it.

**Comment by rajendrant** [comment]
Closing this PR, since there is some discussion in the issue #20.
I will create a shortened PR that enables travis CI for windows.

**Pull request closed without merging**
