### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Romick2005**
Why Object.assign and Object.create needed here? Am I missing something?

### CODE REVIEW

**Comment by derhuerst** [comment]
Yes: We use the object as a dictionary, and we want to avoid a collision between the result of `os.platform()` and the objects built-in prototype chain.

Therefore, we create an object without a prototype. Related but not exactly the same: https://gist.github.com/derhuerst/a585c4916b1c361cc6f0

**Comment by Romick2005** [comment]
> Yes: We use the object as a dictionary, and we want to avoid a collision between the result of `os.platform()` and the objects built-in prototype chain.
> 
> Therefore, we create an object without a prototype. Related but not exactly the same: https://gist.github.com/derhuerst/a585c4916b1c361cc6f0

Ok Got your point. But then if you afraid that there might be a platform name that somehow math the object internal prototypical properties than we can just use Object.prototype.hasOwnProperty?

**Comment by derhuerst** [comment]
> Ok Got your point. But then if you afraid that there might be a platform name that somehow match the object internal prototypical properties than we can just use Object.prototype.hasOwnProperty?

Yes, both `os.platform()` and an object's prototype fields might change at any point in the future.

**Comment by Romick2005** [comment]
> We could, but what's the benefit. From my perspective, all of these are equivalent:

I was thinking about some simplification. And for me it just more clear to have it with hasOwnProperty (even if it very unlikely to have same fields with object prototype). Having hasOwnProperty would explicitly indicate what we are taking care of. I was also thinking of replacing array of architectures with Set that would allow to use Set.has() and not expensive Array.include(), but probably for such small amount of data it wouldn't make sense.

Probably it is just a matter of code style, and your code is very good so we can leave it as is.
Just wanted to share my thoughts, anyway great job on this module. Thank you @derhuerst and @eugeneware!

**Pull request closed without merging**
