### PR TITLE
support proxies

### PR DESCRIPTION
**Pull request by derhuerst**
Implements #36.

@jonah-dev Please check if this works for you. You can install from this branch using `npm install eugeneware/ffmpeg-static#proxy`.

### CODE REVIEW

**Comment by phollweck** [comment]
@jonah-dev Would be really nice if you could merge this :)

**Comment by phollweck** [comment]
I have tested this change locally and can confirm that it works. 👍 

@eugeneware It Would be really nice if you could merge this. :)

**Comment by eugeneware** [comment]
@derhuerst LGTM. I've just tested it with a local HTTP proxy server and it looked good. Feel free to merge and release. :clap:

**Comment by derhuerst** [comment]
Published as `ffmpeg-static@4.2.0`. 🎉

**Pull request merged**
